name: Linux Executable Yap

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: PyInstaller ve Tkinter Kur
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Linux Executable Derle
        run: |
          pyinstaller --onefile --noconsole uslu_isaret.py
      - name: Dosyayi Indirilebilir Yap
        uses: actions/upload-artifact@v4
        with:
          name: linux-programi
          path: dist/uslu_isaret
